### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by modem7** [cwackerfuss/react-wordle#292]
**Describe the bug**
When attempting to build, all I get is a white screen, no content. 

**To Reproduce**
```
name: Deploy
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
      - name: deploy to pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
```

No doubt it's a user error, just curious if someone can assist?
